#!/bin/bash
set -e
cd "$(dirname "$0")"/..
if !( command -v cargo); then
	source ~/.cargo/env
fi
if [ "$1" = "server" ]; then
	cargo run --release --bin ntim_server <(cat ntim_data/*.txt)
elif [ "$1" = "client" ]; then
	cargo run --release --bin ntim_client
	cat /tmp/ntim_rs.txt | xsel -i -b
fi
